// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: datumV3.proto

package cerasus_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DatumClient is the client API for Datum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatumClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	SetQueueJob(ctx context.Context, in *QueuerJob, opts ...grpc.CallOption) (*StatusReply, error)
	GetShopSalesWidget(ctx context.Context, in *RequestByShop, opts ...grpc.CallOption) (*ShopWidget, error)
	GetOrderLeaders(ctx context.Context, in *RequestByShop, opts ...grpc.CallOption) (*OrderLeaders, error)
	GetMainGraphic(ctx context.Context, in *LineGraphRequest, opts ...grpc.CallOption) (*LineGraph, error)
}

type datumClient struct {
	cc grpc.ClientConnInterface
}

func NewDatumClient(cc grpc.ClientConnInterface) DatumClient {
	return &datumClient{cc}
}

func (c *datumClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.Datum/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumClient) SetQueueJob(ctx context.Context, in *QueuerJob, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.Datum/SetQueueJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumClient) GetShopSalesWidget(ctx context.Context, in *RequestByShop, opts ...grpc.CallOption) (*ShopWidget, error) {
	out := new(ShopWidget)
	err := c.cc.Invoke(ctx, "/cerasusV3.Datum/GetShopSalesWidget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumClient) GetOrderLeaders(ctx context.Context, in *RequestByShop, opts ...grpc.CallOption) (*OrderLeaders, error) {
	out := new(OrderLeaders)
	err := c.cc.Invoke(ctx, "/cerasusV3.Datum/GetOrderLeaders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datumClient) GetMainGraphic(ctx context.Context, in *LineGraphRequest, opts ...grpc.CallOption) (*LineGraph, error) {
	out := new(LineGraph)
	err := c.cc.Invoke(ctx, "/cerasusV3.Datum/GetMainGraphic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatumServer is the server API for Datum service.
// All implementations must embed UnimplementedDatumServer
// for forward compatibility
type DatumServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	SetQueueJob(context.Context, *QueuerJob) (*StatusReply, error)
	GetShopSalesWidget(context.Context, *RequestByShop) (*ShopWidget, error)
	GetOrderLeaders(context.Context, *RequestByShop) (*OrderLeaders, error)
	GetMainGraphic(context.Context, *LineGraphRequest) (*LineGraph, error)
	mustEmbedUnimplementedDatumServer()
}

// UnimplementedDatumServer must be embedded to have forward compatible implementations.
type UnimplementedDatumServer struct {
}

func (UnimplementedDatumServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDatumServer) SetQueueJob(context.Context, *QueuerJob) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetQueueJob not implemented")
}
func (UnimplementedDatumServer) GetShopSalesWidget(context.Context, *RequestByShop) (*ShopWidget, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopSalesWidget not implemented")
}
func (UnimplementedDatumServer) GetOrderLeaders(context.Context, *RequestByShop) (*OrderLeaders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderLeaders not implemented")
}
func (UnimplementedDatumServer) GetMainGraphic(context.Context, *LineGraphRequest) (*LineGraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMainGraphic not implemented")
}
func (UnimplementedDatumServer) mustEmbedUnimplementedDatumServer() {}

// UnsafeDatumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatumServer will
// result in compilation errors.
type UnsafeDatumServer interface {
	mustEmbedUnimplementedDatumServer()
}

func RegisterDatumServer(s grpc.ServiceRegistrar, srv DatumServer) {
	s.RegisterService(&Datum_ServiceDesc, srv)
}

func _Datum_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.Datum/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datum_SetQueueJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueuerJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServer).SetQueueJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.Datum/SetQueueJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServer).SetQueueJob(ctx, req.(*QueuerJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datum_GetShopSalesWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByShop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServer).GetShopSalesWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.Datum/GetShopSalesWidget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServer).GetShopSalesWidget(ctx, req.(*RequestByShop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datum_GetOrderLeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByShop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServer).GetOrderLeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.Datum/GetOrderLeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServer).GetOrderLeaders(ctx, req.(*RequestByShop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datum_GetMainGraphic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LineGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatumServer).GetMainGraphic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.Datum/GetMainGraphic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatumServer).GetMainGraphic(ctx, req.(*LineGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Datum_ServiceDesc is the grpc.ServiceDesc for Datum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Datum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerasusV3.Datum",
	HandlerType: (*DatumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Datum_Ping_Handler,
		},
		{
			MethodName: "SetQueueJob",
			Handler:    _Datum_SetQueueJob_Handler,
		},
		{
			MethodName: "GetShopSalesWidget",
			Handler:    _Datum_GetShopSalesWidget_Handler,
		},
		{
			MethodName: "GetOrderLeaders",
			Handler:    _Datum_GetOrderLeaders_Handler,
		},
		{
			MethodName: "GetMainGraphic",
			Handler:    _Datum_GetMainGraphic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datumV3.proto",
}
