// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: oz-apiV3.proto

package cerasus_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OZ_APIClient is the client API for OZ_API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OZ_APIClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetWarehouses(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*Warehouses, error)
	LoadApiOrders(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetApiOrders(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*OZApiOrders, error)
	LoadApiSales(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*StatusReply, error)
	GetApiSales(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*OZApiSales, error)
	LoadApiProducts(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*StatusReply, error)
	GetApiProducts(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*OZApiProducts, error)
	GetApiStocks(ctx context.Context, in *OZApiStockRequest, opts ...grpc.CallOption) (*OZApiStockData, error)
	GetProductsShopPrice(ctx context.Context, in *OZApiStockRequest, opts ...grpc.CallOption) (*OZApiPricesData, error)
	SendNewPrices(ctx context.Context, in *OZApiNewPricesRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type oZ_APIClient struct {
	cc grpc.ClientConnInterface
}

func NewOZ_APIClient(cc grpc.ClientConnInterface) OZ_APIClient {
	return &oZ_APIClient{cc}
}

func (c *oZ_APIClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetWarehouses(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*Warehouses, error) {
	out := new(Warehouses)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/GetWarehouses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) LoadApiOrders(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/LoadApiOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetApiOrders(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*OZApiOrders, error) {
	out := new(OZApiOrders)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/GetApiOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) LoadApiSales(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/LoadApiSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetApiSales(ctx context.Context, in *OZApiOrdersRequest, opts ...grpc.CallOption) (*OZApiSales, error) {
	out := new(OZApiSales)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/GetApiSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) LoadApiProducts(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/LoadApiProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetApiProducts(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*OZApiProducts, error) {
	out := new(OZApiProducts)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/GetApiProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetApiStocks(ctx context.Context, in *OZApiStockRequest, opts ...grpc.CallOption) (*OZApiStockData, error) {
	out := new(OZApiStockData)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/GetApiStocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetProductsShopPrice(ctx context.Context, in *OZApiStockRequest, opts ...grpc.CallOption) (*OZApiPricesData, error) {
	out := new(OZApiPricesData)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/GetProductsShopPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) SendNewPrices(ctx context.Context, in *OZApiNewPricesRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, "/cerasusV3.OZ_API/SendNewPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OZ_APIServer is the server API for OZ_API service.
// All implementations must embed UnimplementedOZ_APIServer
// for forward compatibility
type OZ_APIServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetWarehouses(context.Context, *OZAuthParams) (*Warehouses, error)
	LoadApiOrders(context.Context, *OZApiOrdersRequest) (*StatusReply, error)
	GetApiOrders(context.Context, *OZApiOrdersRequest) (*OZApiOrders, error)
	LoadApiSales(context.Context, *OZApiOrdersRequest) (*StatusReply, error)
	GetApiSales(context.Context, *OZApiOrdersRequest) (*OZApiSales, error)
	LoadApiProducts(context.Context, *OZAuthParams) (*StatusReply, error)
	GetApiProducts(context.Context, *OZAuthParams) (*OZApiProducts, error)
	GetApiStocks(context.Context, *OZApiStockRequest) (*OZApiStockData, error)
	GetProductsShopPrice(context.Context, *OZApiStockRequest) (*OZApiPricesData, error)
	SendNewPrices(context.Context, *OZApiNewPricesRequest) (*StatusReply, error)
	mustEmbedUnimplementedOZ_APIServer()
}

// UnimplementedOZ_APIServer must be embedded to have forward compatible implementations.
type UnimplementedOZ_APIServer struct {
}

func (UnimplementedOZ_APIServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOZ_APIServer) GetWarehouses(context.Context, *OZAuthParams) (*Warehouses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWarehouses not implemented")
}
func (UnimplementedOZ_APIServer) LoadApiOrders(context.Context, *OZApiOrdersRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadApiOrders not implemented")
}
func (UnimplementedOZ_APIServer) GetApiOrders(context.Context, *OZApiOrdersRequest) (*OZApiOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiOrders not implemented")
}
func (UnimplementedOZ_APIServer) LoadApiSales(context.Context, *OZApiOrdersRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadApiSales not implemented")
}
func (UnimplementedOZ_APIServer) GetApiSales(context.Context, *OZApiOrdersRequest) (*OZApiSales, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiSales not implemented")
}
func (UnimplementedOZ_APIServer) LoadApiProducts(context.Context, *OZAuthParams) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadApiProducts not implemented")
}
func (UnimplementedOZ_APIServer) GetApiProducts(context.Context, *OZAuthParams) (*OZApiProducts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiProducts not implemented")
}
func (UnimplementedOZ_APIServer) GetApiStocks(context.Context, *OZApiStockRequest) (*OZApiStockData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiStocks not implemented")
}
func (UnimplementedOZ_APIServer) GetProductsShopPrice(context.Context, *OZApiStockRequest) (*OZApiPricesData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsShopPrice not implemented")
}
func (UnimplementedOZ_APIServer) SendNewPrices(context.Context, *OZApiNewPricesRequest) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNewPrices not implemented")
}
func (UnimplementedOZ_APIServer) mustEmbedUnimplementedOZ_APIServer() {}

// UnsafeOZ_APIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OZ_APIServer will
// result in compilation errors.
type UnsafeOZ_APIServer interface {
	mustEmbedUnimplementedOZ_APIServer()
}

func RegisterOZ_APIServer(s grpc.ServiceRegistrar, srv OZ_APIServer) {
	s.RegisterService(&OZ_API_ServiceDesc, srv)
}

func _OZ_API_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetWarehouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZAuthParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetWarehouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/GetWarehouses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetWarehouses(ctx, req.(*OZAuthParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_LoadApiOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).LoadApiOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/LoadApiOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).LoadApiOrders(ctx, req.(*OZApiOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetApiOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetApiOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/GetApiOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetApiOrders(ctx, req.(*OZApiOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_LoadApiSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).LoadApiSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/LoadApiSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).LoadApiSales(ctx, req.(*OZApiOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetApiSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetApiSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/GetApiSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetApiSales(ctx, req.(*OZApiOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_LoadApiProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZAuthParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).LoadApiProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/LoadApiProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).LoadApiProducts(ctx, req.(*OZAuthParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetApiProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZAuthParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetApiProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/GetApiProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetApiProducts(ctx, req.(*OZAuthParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetApiStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetApiStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/GetApiStocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetApiStocks(ctx, req.(*OZApiStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetProductsShopPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetProductsShopPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/GetProductsShopPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetProductsShopPrice(ctx, req.(*OZApiStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_SendNewPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZApiNewPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).SendNewPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV3.OZ_API/SendNewPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).SendNewPrices(ctx, req.(*OZApiNewPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OZ_API_ServiceDesc is the grpc.ServiceDesc for OZ_API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OZ_API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerasusV3.OZ_API",
	HandlerType: (*OZ_APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OZ_API_Ping_Handler,
		},
		{
			MethodName: "GetWarehouses",
			Handler:    _OZ_API_GetWarehouses_Handler,
		},
		{
			MethodName: "LoadApiOrders",
			Handler:    _OZ_API_LoadApiOrders_Handler,
		},
		{
			MethodName: "GetApiOrders",
			Handler:    _OZ_API_GetApiOrders_Handler,
		},
		{
			MethodName: "LoadApiSales",
			Handler:    _OZ_API_LoadApiSales_Handler,
		},
		{
			MethodName: "GetApiSales",
			Handler:    _OZ_API_GetApiSales_Handler,
		},
		{
			MethodName: "LoadApiProducts",
			Handler:    _OZ_API_LoadApiProducts_Handler,
		},
		{
			MethodName: "GetApiProducts",
			Handler:    _OZ_API_GetApiProducts_Handler,
		},
		{
			MethodName: "GetApiStocks",
			Handler:    _OZ_API_GetApiStocks_Handler,
		},
		{
			MethodName: "GetProductsShopPrice",
			Handler:    _OZ_API_GetProductsShopPrice_Handler,
		},
		{
			MethodName: "SendNewPrices",
			Handler:    _OZ_API_SendNewPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oz-apiV3.proto",
}
