// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: brand.proto

package cerasus_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrandsClient is the client API for Brands service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrandsClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetBrandData(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Brand, error)
	GetBProducts(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*BProducts, error)
	GetBProduct(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BProduct, error)
	CreateBProduct(ctx context.Context, in *BProductUpsert, opts ...grpc.CallOption) (*BProduct, error)
	UpdateBProduct(ctx context.Context, in *BProductUpsert, opts ...grpc.CallOption) (*BoolReply, error)
	DeleteBProduct(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BoolReply, error)
	GetBFile(ctx context.Context, in *BFileRequest, opts ...grpc.CallOption) (*ImageReply, error)
	UploadBFile(ctx context.Context, in *BUploadRequest, opts ...grpc.CallOption) (*ImageReply, error)
	GetBPrices(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BPrices, error)
	GetBPrice(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BPrice, error)
	CreateBPrice(ctx context.Context, in *BPriceUpsert, opts ...grpc.CallOption) (*BPrice, error)
	DeleteBPrice(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BoolReply, error)
	CreateBSeller(ctx context.Context, in *BSellerUpsert, opts ...grpc.CallOption) (*BSeller, error)
	GetBSellers(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*BSellers, error)
	GetBSeller(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BSeller, error)
	UpdateBSeller(ctx context.Context, in *BSellerUpsert, opts ...grpc.CallOption) (*BoolReply, error)
	DeleteBSeller(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BoolReply, error)
}

type brandsClient struct {
	cc grpc.ClientConnInterface
}

func NewBrandsClient(cc grpc.ClientConnInterface) BrandsClient {
	return &brandsClient{cc}
}

func (c *brandsClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBrandData(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Brand, error) {
	out := new(Brand)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBrandData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBProducts(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*BProducts, error) {
	out := new(BProducts)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBProduct(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BProduct, error) {
	out := new(BProduct)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) CreateBProduct(ctx context.Context, in *BProductUpsert, opts ...grpc.CallOption) (*BProduct, error) {
	out := new(BProduct)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/CreateBProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) UpdateBProduct(ctx context.Context, in *BProductUpsert, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/UpdateBProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) DeleteBProduct(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/DeleteBProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBFile(ctx context.Context, in *BFileRequest, opts ...grpc.CallOption) (*ImageReply, error) {
	out := new(ImageReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) UploadBFile(ctx context.Context, in *BUploadRequest, opts ...grpc.CallOption) (*ImageReply, error) {
	out := new(ImageReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/UploadBFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBPrices(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BPrices, error) {
	out := new(BPrices)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBPrice(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BPrice, error) {
	out := new(BPrice)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) CreateBPrice(ctx context.Context, in *BPriceUpsert, opts ...grpc.CallOption) (*BPrice, error) {
	out := new(BPrice)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/CreateBPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) DeleteBPrice(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/DeleteBPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) CreateBSeller(ctx context.Context, in *BSellerUpsert, opts ...grpc.CallOption) (*BSeller, error) {
	out := new(BSeller)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/CreateBSeller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBSellers(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*BSellers, error) {
	out := new(BSellers)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBSellers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) GetBSeller(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BSeller, error) {
	out := new(BSeller)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/GetBSeller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) UpdateBSeller(ctx context.Context, in *BSellerUpsert, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/UpdateBSeller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brandsClient) DeleteBSeller(ctx context.Context, in *RequestByID, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := c.cc.Invoke(ctx, "/cerasus.Brands/DeleteBSeller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrandsServer is the server API for Brands service.
// All implementations must embed UnimplementedBrandsServer
// for forward compatibility
type BrandsServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetBrandData(context.Context, *Auth) (*Brand, error)
	GetBProducts(context.Context, *Auth) (*BProducts, error)
	GetBProduct(context.Context, *RequestByID) (*BProduct, error)
	CreateBProduct(context.Context, *BProductUpsert) (*BProduct, error)
	UpdateBProduct(context.Context, *BProductUpsert) (*BoolReply, error)
	DeleteBProduct(context.Context, *RequestByID) (*BoolReply, error)
	GetBFile(context.Context, *BFileRequest) (*ImageReply, error)
	UploadBFile(context.Context, *BUploadRequest) (*ImageReply, error)
	GetBPrices(context.Context, *RequestByID) (*BPrices, error)
	GetBPrice(context.Context, *RequestByID) (*BPrice, error)
	CreateBPrice(context.Context, *BPriceUpsert) (*BPrice, error)
	DeleteBPrice(context.Context, *RequestByID) (*BoolReply, error)
	CreateBSeller(context.Context, *BSellerUpsert) (*BSeller, error)
	GetBSellers(context.Context, *Auth) (*BSellers, error)
	GetBSeller(context.Context, *RequestByID) (*BSeller, error)
	UpdateBSeller(context.Context, *BSellerUpsert) (*BoolReply, error)
	DeleteBSeller(context.Context, *RequestByID) (*BoolReply, error)
	mustEmbedUnimplementedBrandsServer()
}

// UnimplementedBrandsServer must be embedded to have forward compatible implementations.
type UnimplementedBrandsServer struct {
}

func (UnimplementedBrandsServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBrandsServer) GetBrandData(context.Context, *Auth) (*Brand, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrandData not implemented")
}
func (UnimplementedBrandsServer) GetBProducts(context.Context, *Auth) (*BProducts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBProducts not implemented")
}
func (UnimplementedBrandsServer) GetBProduct(context.Context, *RequestByID) (*BProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBProduct not implemented")
}
func (UnimplementedBrandsServer) CreateBProduct(context.Context, *BProductUpsert) (*BProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBProduct not implemented")
}
func (UnimplementedBrandsServer) UpdateBProduct(context.Context, *BProductUpsert) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBProduct not implemented")
}
func (UnimplementedBrandsServer) DeleteBProduct(context.Context, *RequestByID) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBProduct not implemented")
}
func (UnimplementedBrandsServer) GetBFile(context.Context, *BFileRequest) (*ImageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBFile not implemented")
}
func (UnimplementedBrandsServer) UploadBFile(context.Context, *BUploadRequest) (*ImageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBFile not implemented")
}
func (UnimplementedBrandsServer) GetBPrices(context.Context, *RequestByID) (*BPrices, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBPrices not implemented")
}
func (UnimplementedBrandsServer) GetBPrice(context.Context, *RequestByID) (*BPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBPrice not implemented")
}
func (UnimplementedBrandsServer) CreateBPrice(context.Context, *BPriceUpsert) (*BPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBPrice not implemented")
}
func (UnimplementedBrandsServer) DeleteBPrice(context.Context, *RequestByID) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBPrice not implemented")
}
func (UnimplementedBrandsServer) CreateBSeller(context.Context, *BSellerUpsert) (*BSeller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBSeller not implemented")
}
func (UnimplementedBrandsServer) GetBSellers(context.Context, *Auth) (*BSellers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBSellers not implemented")
}
func (UnimplementedBrandsServer) GetBSeller(context.Context, *RequestByID) (*BSeller, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBSeller not implemented")
}
func (UnimplementedBrandsServer) UpdateBSeller(context.Context, *BSellerUpsert) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBSeller not implemented")
}
func (UnimplementedBrandsServer) DeleteBSeller(context.Context, *RequestByID) (*BoolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBSeller not implemented")
}
func (UnimplementedBrandsServer) mustEmbedUnimplementedBrandsServer() {}

// UnsafeBrandsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrandsServer will
// result in compilation errors.
type UnsafeBrandsServer interface {
	mustEmbedUnimplementedBrandsServer()
}

func RegisterBrandsServer(s grpc.ServiceRegistrar, srv BrandsServer) {
	s.RegisterService(&Brands_ServiceDesc, srv)
}

func _Brands_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBrandData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBrandData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBrandData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBrandData(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBProducts(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBProduct(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_CreateBProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BProductUpsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).CreateBProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/CreateBProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).CreateBProduct(ctx, req.(*BProductUpsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_UpdateBProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BProductUpsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).UpdateBProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/UpdateBProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).UpdateBProduct(ctx, req.(*BProductUpsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_DeleteBProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).DeleteBProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/DeleteBProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).DeleteBProduct(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBFile(ctx, req.(*BFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_UploadBFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).UploadBFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/UploadBFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).UploadBFile(ctx, req.(*BUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBPrices(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBPrice(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_CreateBPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BPriceUpsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).CreateBPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/CreateBPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).CreateBPrice(ctx, req.(*BPriceUpsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_DeleteBPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).DeleteBPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/DeleteBPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).DeleteBPrice(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_CreateBSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BSellerUpsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).CreateBSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/CreateBSeller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).CreateBSeller(ctx, req.(*BSellerUpsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBSellers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBSellers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBSellers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBSellers(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_GetBSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).GetBSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/GetBSeller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).GetBSeller(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_UpdateBSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BSellerUpsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).UpdateBSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/UpdateBSeller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).UpdateBSeller(ctx, req.(*BSellerUpsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Brands_DeleteBSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrandsServer).DeleteBSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasus.Brands/DeleteBSeller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrandsServer).DeleteBSeller(ctx, req.(*RequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

// Brands_ServiceDesc is the grpc.ServiceDesc for Brands service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Brands_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerasus.Brands",
	HandlerType: (*BrandsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Brands_Ping_Handler,
		},
		{
			MethodName: "GetBrandData",
			Handler:    _Brands_GetBrandData_Handler,
		},
		{
			MethodName: "GetBProducts",
			Handler:    _Brands_GetBProducts_Handler,
		},
		{
			MethodName: "GetBProduct",
			Handler:    _Brands_GetBProduct_Handler,
		},
		{
			MethodName: "CreateBProduct",
			Handler:    _Brands_CreateBProduct_Handler,
		},
		{
			MethodName: "UpdateBProduct",
			Handler:    _Brands_UpdateBProduct_Handler,
		},
		{
			MethodName: "DeleteBProduct",
			Handler:    _Brands_DeleteBProduct_Handler,
		},
		{
			MethodName: "GetBFile",
			Handler:    _Brands_GetBFile_Handler,
		},
		{
			MethodName: "UploadBFile",
			Handler:    _Brands_UploadBFile_Handler,
		},
		{
			MethodName: "GetBPrices",
			Handler:    _Brands_GetBPrices_Handler,
		},
		{
			MethodName: "GetBPrice",
			Handler:    _Brands_GetBPrice_Handler,
		},
		{
			MethodName: "CreateBPrice",
			Handler:    _Brands_CreateBPrice_Handler,
		},
		{
			MethodName: "DeleteBPrice",
			Handler:    _Brands_DeleteBPrice_Handler,
		},
		{
			MethodName: "CreateBSeller",
			Handler:    _Brands_CreateBSeller_Handler,
		},
		{
			MethodName: "GetBSellers",
			Handler:    _Brands_GetBSellers_Handler,
		},
		{
			MethodName: "GetBSeller",
			Handler:    _Brands_GetBSeller_Handler,
		},
		{
			MethodName: "UpdateBSeller",
			Handler:    _Brands_UpdateBSeller_Handler,
		},
		{
			MethodName: "DeleteBSeller",
			Handler:    _Brands_DeleteBSeller_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brand.proto",
}
