// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: oz-api_v2.proto

package cerasus_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OZ_APIClient is the client API for OZ_API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OZ_APIClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetWarehouses(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*Warehouses, error)
}

type oZ_APIClient struct {
	cc grpc.ClientConnInterface
}

func NewOZ_APIClient(cc grpc.ClientConnInterface) OZ_APIClient {
	return &oZ_APIClient{cc}
}

func (c *oZ_APIClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cerasusV2.OZ_API/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oZ_APIClient) GetWarehouses(ctx context.Context, in *OZAuthParams, opts ...grpc.CallOption) (*Warehouses, error) {
	out := new(Warehouses)
	err := c.cc.Invoke(ctx, "/cerasusV2.OZ_API/GetWarehouses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OZ_APIServer is the server API for OZ_API service.
// All implementations must embed UnimplementedOZ_APIServer
// for forward compatibility
type OZ_APIServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetWarehouses(context.Context, *OZAuthParams) (*Warehouses, error)
	mustEmbedUnimplementedOZ_APIServer()
}

// UnimplementedOZ_APIServer must be embedded to have forward compatible implementations.
type UnimplementedOZ_APIServer struct {
}

func (UnimplementedOZ_APIServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOZ_APIServer) GetWarehouses(context.Context, *OZAuthParams) (*Warehouses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWarehouses not implemented")
}
func (UnimplementedOZ_APIServer) mustEmbedUnimplementedOZ_APIServer() {}

// UnsafeOZ_APIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OZ_APIServer will
// result in compilation errors.
type UnsafeOZ_APIServer interface {
	mustEmbedUnimplementedOZ_APIServer()
}

func RegisterOZ_APIServer(s grpc.ServiceRegistrar, srv OZ_APIServer) {
	s.RegisterService(&OZ_API_ServiceDesc, srv)
}

func _OZ_API_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV2.OZ_API/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OZ_API_GetWarehouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OZAuthParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OZ_APIServer).GetWarehouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV2.OZ_API/GetWarehouses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OZ_APIServer).GetWarehouses(ctx, req.(*OZAuthParams))
	}
	return interceptor(ctx, in, info, handler)
}

// OZ_API_ServiceDesc is the grpc.ServiceDesc for OZ_API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OZ_API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerasusV2.OZ_API",
	HandlerType: (*OZ_APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OZ_API_Ping_Handler,
		},
		{
			MethodName: "GetWarehouses",
			Handler:    _OZ_API_GetWarehouses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oz-api_v2.proto",
}
