// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: queuer_v2.proto

package cerasus_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueuerClient is the client API for Queuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueuerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type queuerClient struct {
	cc grpc.ClientConnInterface
}

func NewQueuerClient(cc grpc.ClientConnInterface) QueuerClient {
	return &queuerClient{cc}
}

func (c *queuerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/cerasusV2.Queuer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueuerServer is the server API for Queuer service.
// All implementations must embed UnimplementedQueuerServer
// for forward compatibility
type QueuerServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	mustEmbedUnimplementedQueuerServer()
}

// UnimplementedQueuerServer must be embedded to have forward compatible implementations.
type UnimplementedQueuerServer struct {
}

func (UnimplementedQueuerServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedQueuerServer) mustEmbedUnimplementedQueuerServer() {}

// UnsafeQueuerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueuerServer will
// result in compilation errors.
type UnsafeQueuerServer interface {
	mustEmbedUnimplementedQueuerServer()
}

func RegisterQueuerServer(s grpc.ServiceRegistrar, srv QueuerServer) {
	s.RegisterService(&Queuer_ServiceDesc, srv)
}

func _Queuer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cerasusV2.Queuer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Queuer_ServiceDesc is the grpc.ServiceDesc for Queuer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Queuer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cerasusV2.Queuer",
	HandlerType: (*QueuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Queuer_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queuer_v2.proto",
}
