// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: wb-data_v2.proto

package cerasus_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WBAuthData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth  *Auth  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *WBAuthData) Reset() {
	*x = WBAuthData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wb_data_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WBAuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WBAuthData) ProtoMessage() {}

func (x *WBAuthData) ProtoReflect() protoreflect.Message {
	mi := &file_wb_data_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WBAuthData.ProtoReflect.Descriptor instead.
func (*WBAuthData) Descriptor() ([]byte, []int) {
	return file_wb_data_v2_proto_rawDescGZIP(), []int{0}
}

func (x *WBAuthData) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *WBAuthData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WBAuthParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth  *Auth  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *WBAuthParams) Reset() {
	*x = WBAuthParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wb_data_v2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WBAuthParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WBAuthParams) ProtoMessage() {}

func (x *WBAuthParams) ProtoReflect() protoreflect.Message {
	mi := &file_wb_data_v2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WBAuthParams.ProtoReflect.Descriptor instead.
func (*WBAuthParams) Descriptor() ([]byte, []int) {
	return file_wb_data_v2_proto_rawDescGZIP(), []int{1}
}

func (x *WBAuthParams) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *WBAuthParams) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WBCounterParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token        string         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Warehouses   []int64        `protobuf:"varint,2,rep,packed,name=warehouses,proto3" json:"warehouses,omitempty"`
	ShopProducts []*ShopProduct `protobuf:"bytes,3,rep,name=shopProducts,proto3" json:"shopProducts,omitempty"`
}

func (x *WBCounterParams) Reset() {
	*x = WBCounterParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wb_data_v2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WBCounterParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WBCounterParams) ProtoMessage() {}

func (x *WBCounterParams) ProtoReflect() protoreflect.Message {
	mi := &file_wb_data_v2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WBCounterParams.ProtoReflect.Descriptor instead.
func (*WBCounterParams) Descriptor() ([]byte, []int) {
	return file_wb_data_v2_proto_rawDescGZIP(), []int{2}
}

func (x *WBCounterParams) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WBCounterParams) GetWarehouses() []int64 {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

func (x *WBCounterParams) GetShopProducts() []*ShopProduct {
	if x != nil {
		return x.ShopProducts
	}
	return nil
}

var File_wb_data_v2_proto protoreflect.FileDescriptor

var file_wb_data_v2_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x62, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x63, 0x65, 0x72, 0x61, 0x73, 0x75, 0x73, 0x56, 0x32, 0x1a, 0x10, 0x63,
	0x65, 0x72, 0x61, 0x73, 0x75, 0x73, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x47, 0x0a, 0x0a, 0x57, 0x42, 0x41, 0x75, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65,
	0x72, 0x61, 0x73, 0x75, 0x73, 0x56, 0x32, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x49, 0x0a, 0x0c, 0x57, 0x42, 0x41, 0x75,
	0x74, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x72, 0x61, 0x73, 0x75, 0x73,
	0x56, 0x32, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x57, 0x42, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0a, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x12, 0x3a, 0x0a,
	0x0c, 0x73, 0x68, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x65, 0x72, 0x61, 0x73, 0x75, 0x73, 0x56, 0x32, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x0c, 0x73, 0x68, 0x6f,
	0x70, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x73, 0x61, 0x6e, 0x79, 0x63, 0x68,
	0x2f, 0x63, 0x65, 0x72, 0x61, 0x73, 0x75, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wb_data_v2_proto_rawDescOnce sync.Once
	file_wb_data_v2_proto_rawDescData = file_wb_data_v2_proto_rawDesc
)

func file_wb_data_v2_proto_rawDescGZIP() []byte {
	file_wb_data_v2_proto_rawDescOnce.Do(func() {
		file_wb_data_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_wb_data_v2_proto_rawDescData)
	})
	return file_wb_data_v2_proto_rawDescData
}

var file_wb_data_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wb_data_v2_proto_goTypes = []interface{}{
	(*WBAuthData)(nil),      // 0: cerasusV2.WBAuthData
	(*WBAuthParams)(nil),    // 1: cerasusV2.WBAuthParams
	(*WBCounterParams)(nil), // 2: cerasusV2.WBCounterParams
	(*Auth)(nil),            // 3: cerasusV2.Auth
	(*ShopProduct)(nil),     // 4: cerasusV2.ShopProduct
}
var file_wb_data_v2_proto_depIdxs = []int32{
	3, // 0: cerasusV2.WBAuthData.auth:type_name -> cerasusV2.Auth
	3, // 1: cerasusV2.WBAuthParams.auth:type_name -> cerasusV2.Auth
	4, // 2: cerasusV2.WBCounterParams.shopProducts:type_name -> cerasusV2.ShopProduct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wb_data_v2_proto_init() }
func file_wb_data_v2_proto_init() {
	if File_wb_data_v2_proto != nil {
		return
	}
	file_cerasus_v2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wb_data_v2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WBAuthData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wb_data_v2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WBAuthParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wb_data_v2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WBCounterParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wb_data_v2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wb_data_v2_proto_goTypes,
		DependencyIndexes: file_wb_data_v2_proto_depIdxs,
		MessageInfos:      file_wb_data_v2_proto_msgTypes,
	}.Build()
	File_wb_data_v2_proto = out.File
	file_wb_data_v2_proto_rawDesc = nil
	file_wb_data_v2_proto_goTypes = nil
	file_wb_data_v2_proto_depIdxs = nil
}
